const authRouters = require('../routes/auth')
const therapistRouter = require('../routes/therapistRoutes')
const patientRouter = require('../routes/patient-routes')
const sessionRouter = require('../routes/sessionsRoter')
const subsRouter = require('../routes/subscriptionRoutes')
const postRouter = require('../routes/postRoutes')
const commentRouter = require('../routes/commentRoutes')
const paymentRouter = require('../routes/paymentRoutes')
const blacklistRouter = require('../routes/blacklistRoutes')
const reviewRouter = require('../routes/reviewRoutes')
const storiesRouter = require('../routes/storiesRoutes')
const notFound = require('../middlewares/not-found')
const errorHandler = require('../middlewares/error-handler')
const list_end_points = require('list_end_points')

module.exports = (app)=>{
app.use('/api/v1/auth', authRouters)
app.use('/api/v1/therapists', therapistRouter)
app.use('/api/v1/patients', patientRouter)
app.use('/api/v1/sessions', sessionRouter)
app.use('/api/v1/subscriptions', subsRouter)
app.use('/api/v1/posts', postRouter)
app.use('/api/v1/comments', commentRouter)
app.use('/api/v1/stories', storiesRouter)
app.use('/api/v1/reviews', reviewRouter)
app.use('/api/v1/payments', paymentRouter)
app.use('/api/v1/blacklists', blacklistRouter)
app.use(notFound)
app.use(errorHandler)
list_end_points(app)
}
